apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo  
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: demo
        image: kortstieacr.azurecr.io/sampleapp:v1  
        ports:
        - containerPort: 5000
        env:
        - name: TITLE
          value: "Welcome to Azure Kubernetes Service (AKS)"
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
              