on: [push]
name: Linux_Container_Workflow

env:
  REGISTRY_LOGIN_SERVER: ${{ vars.PROJECT_NAME }}acr.azurecr.io
  RESOURCE_GROUP: ${{ vars.PROJECT_NAME }}rg
  AKS_CLUSTER_NAME: ${{ vars.PROJECT_NAME }}aks

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:

        - name: 'Checkout this GitHub repo'
          uses: actions/checkout@main

        - name: 'Set our registry name in the deployment manifest'
          run: |
            sed -i 's#REPLACE_ME_REGISTRY_NAME#${{ env.REGISTRY_LOGIN_SERVER }}#' k8s-manifests/20-deployment.yaml
        
        - name: 'Build and push image'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ env.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        - run: |
            docker build . -t ${{ env.REGISTRY_LOGIN_SERVER }}/sampleapp:${{ github.run_id }}
            docker push ${{ env.REGISTRY_LOGIN_SERVER }}/sampleapp:${{ github.run_id }}

        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}

        - name: 'set AKS context'
          uses: azure/aks-set-context@v3
          with:
            resource-group: '${{ env.RESOURCE_GROUP }}'
            cluster-name: '${{ env.AKS_CLUSTER_NAME }}'

        - name: 'create demo namespace'
          uses: Azure/k8s-deploy@v5
          with:
            manifests: k8s-manifests/10-namespace.yaml
             
        - name: 'Deploy our app to AKS'
          uses: Azure/k8s-deploy@v5
          with:
            manifests: |
              k8s-manifests/20-deployment.yaml
              k8s-manifests/30-service.yaml
              k8s-manifests/40-rbac.yaml
            namespace: demo
            images: '${{ env.REGISTRY_LOGIN_SERVER }}/sampleapp:${{ github.run_id }}'
  