on: [push]
name: Linux_Container_Workflow

jobs:
    build-and-push-image:
        runs-on: ubuntu-latest
        steps:

        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main

        - name: 'Build and push image'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        - run: |
            docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/sampleapp:${{ github.run_id }}
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/sampleapp:${{ github.run_id }}

    deply-to-aks:
        needs: build-and-push-image
        runs-on: ubuntu-latest
        steps:

        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
          
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}

        - name: 'set AKS context'
          uses: azure/aks-set-context@v3
          with:
            resource-group: 'kortstierg'
            cluster-name: 'kortstieaks'

        - name: 'create demo namespace'
          uses: Azure/k8s-deploy@v5
          with:
            manifests: k8s-manifests/10-namespace.yaml
             
        - name: 'Deploy to AKS'
          uses: Azure/k8s-deploy@v5
          with:
            manifests: |
              k8s-manifests/20-deployment.yaml
              k8s-manifests/30-service.yaml
            namespace: demo
            images: '${{ secrets.REGISTRY_LOGIN_SERVER }}/sampleapp:${{ github.run_id }}'
  